"""JAX-native physics kernels that preserve MIMIC model semantics."""

from mimic_jax import reporting, sage16
from mimic_jax.numerics import (
    FIXED_STEP_METHODS,
    FORWARD_EULER,
    HEUN_RK2,
    RK4,
    FixedStepSolution,
    MethodConvergenceResult,
    TimestepRefinementResult,
    conservation_residual,
    fixed_step_rhs_evaluations,
    fixed_step_update,
    integrate_fixed_step,
    method_convergence_study,
    step_to_timescale_ratio,
    timestep_refinement_study,
)
from mimic_jax.sensitivity import (
    LOG_ELASTICITY,
    PROCESS_LOG_RESPONSE,
    REFERENCE_SCALE,
    HistoricalProcessResponse,
    InvalidNormalizationError,
    ParameterResponseMatrix,
    finite_epoch_magnitude_weights,
    ln_scale_factor,
    parameter_response_matrix,
    process_response_tensor,
    redshift_from_ln_scale_factor,
    response_similarity,
    uniform_ln_scale_factor_edges,
    validate_parameter_response,
    validate_process_response,
)

__all__ = [
    "LOG_ELASTICITY",
    "PROCESS_LOG_RESPONSE",
    "REFERENCE_SCALE",
    "HistoricalProcessResponse",
    "InvalidNormalizationError",
    "FIXED_STEP_METHODS",
    "FORWARD_EULER",
    "FixedStepSolution",
    "HEUN_RK2",
    "MethodConvergenceResult",
    "ParameterResponseMatrix",
    "RK4",
    "TimestepRefinementResult",
    "conservation_residual",
    "finite_epoch_magnitude_weights",
    "fixed_step_rhs_evaluations",
    "fixed_step_update",
    "integrate_fixed_step",
    "ln_scale_factor",
    "method_convergence_study",
    "parameter_response_matrix",
    "process_response_tensor",
    "redshift_from_ln_scale_factor",
    "response_similarity",
    "reporting",
    "sage16",
    "step_to_timescale_ratio",
    "timestep_refinement_study",
    "uniform_ln_scale_factor_edges",
    "validate_parameter_response",
    "validate_process_response",
]
