"""Self-documenting run and comparison reports for mimic-jax science products."""

from mimic_jax.reporting.diagnostics import (
    benchmark_diagnostic,
    conservation_diagnostic,
    equivalence_diagnostic,
    historical_response_diagnostic,
    ode_convergence_diagnostic,
    parameter_response_diagnostic,
    parameters_from_namedtuple,
    timestep_refinement_diagnostic,
)
from mimic_jax.reporting.model import (
    REPORT_SCHEMA_VERSION,
    Artifact,
    ComparedRun,
    ComparisonMetric,
    ComparisonReport,
    Diagnostic,
    DiagnosticStatus,
    ParameterValue,
    Provenance,
    ProvenanceFile,
    ReportLink,
    ReportSection,
    RunIdentity,
    RunReport,
    ScalarMetric,
)
from mimic_jax.reporting.provenance import (
    capture_provenance,
    checksummed_file,
    load_upstream_run_record,
)
from mimic_jax.reporting.render import (
    WrittenReport,
    render_comparison_markdown,
    render_markdown,
    render_run_markdown,
    resolve_artifacts,
    write_report,
)

__all__ = [
    "REPORT_SCHEMA_VERSION",
    "Artifact",
    "ComparedRun",
    "ComparisonMetric",
    "ComparisonReport",
    "Diagnostic",
    "DiagnosticStatus",
    "ParameterValue",
    "Provenance",
    "ProvenanceFile",
    "ReportLink",
    "ReportSection",
    "RunIdentity",
    "RunReport",
    "ScalarMetric",
    "WrittenReport",
    "benchmark_diagnostic",
    "capture_provenance",
    "checksummed_file",
    "conservation_diagnostic",
    "equivalence_diagnostic",
    "historical_response_diagnostic",
    "load_upstream_run_record",
    "ode_convergence_diagnostic",
    "parameter_response_diagnostic",
    "parameters_from_namedtuple",
    "render_comparison_markdown",
    "render_markdown",
    "render_run_markdown",
    "resolve_artifacts",
    "timestep_refinement_diagnostic",
    "write_report",
]
